### PR TITLE
Scroll Label added

### PR DESCRIPTION
**Pull request by Apurwa11-894**
Scrollabel added in cube testig page.

### CODE REVIEW

**Review by smartdusttechnologies — COMMENTED** [review]
Correct file name spelling : TestingAndCalibrationLabs/TestingAndCalibrationLabs.Web.UI/Views/Common/Components/ProgressStatus/_progressStatusWithWorklofw.cshtml

**Comment by Apurwa11-894** [comment]
@smartdusttechnologies  Sir  i have not created any file already exist these name.

**Comment by rajguptaH** [comment]
Apurva Rename TestingAndCalibrationLabs/TestingAndCalibrationLabs.Web.UI/Views/Common/Components/ProgressStatus/_progressStatusWithWorklofw.cshtml to TestingAndCalibrationLabs/TestingAndCalibrationLabs.Web.UI/Views/Common/Components/ProgressStatus/_progressStatusWithWorkflow.cshtml

**Comment by rajguptaH** [comment]
seed data not working ?? I cant test this is local

**Pull request merged**
